source 'https://rubygems.org'

gem 'sinatra', '~> 2.0.2'
gem 'sinatra-contrib'
gem 'haml'
gem 'bson_ext'
gem 'faraday'
gem 'puma'
gem 'prometheus-client', "~> 0.9.0"
gem 'rack'
gem 'rufus-scheduler'
gem 'tzinfo-data'
gem 'zipkin-tracer'
